old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        download_files:
            class: App\Producer\DownloadFiles
            connection: default
            exchange_options: { name: 'download-files', type: direct }
        parse_files:
            class: App\Producer\ParseFiles
            connection: default
            exchange_options: { name: 'parse-files', type: direct }
        check_products:
            class: App\Producer\CheckProducts
            connection: default
            exchange_options: { name: 'check-products', type: direct }
            #service_alias:    my_app_service # no alias by default
        update_products:
            class: App\Producer\UpdateProducts
            connection: default
            exchange_options: { name: 'update-products', type: direct }
            #service_alias:    my_app_service # no alias by default
        create_products:
            class: App\Producer\CreateProducts
            connection: default
            exchange_options: { name: 'create-products', type: direct }
            #service_alias:    my_app_service # no alias by default
    consumers:
        download_file:
            connection: default
            exchange_options: { name: 'download-files', type: direct }
            queue_options: { name: 'download-file' }
            callback: download_service
        parse_file:
            connection: default
            exchange_options: { name: 'parse-files', type: direct }
            queue_options: { name: 'parse-file' }
            callback: parse_service
        check_product:
            connection: default
            exchange_options: { name: 'check-products', type: direct }
            queue_options: { name: 'check-product' }
            callback: checkproduct_service
        update_product:
            connection: default
            exchange_options: { name: 'update-products', type: direct }
            queue_options: { name: 'update-product' }
            callback: updateproduct_service
        create_product:
            connection: default
            exchange_options: { name: 'create-products', type: direct }
            queue_options: { name: 'create-product' }
            callback: createproduct_service
